image: Ubuntu2204  # Образ для сборки (Ubuntu 22.04)

stack: node 20  # Окружение (Node.js 20)

branches:
  only:
    - master  # Ветка git (master)
    - main    # Ветка git (main)

cache: 
  - frontend/node_modules  # Кешируем только папку node_modules фронтенда

install:
  - cd frontend && npm install  # Устанавливаем зависимости только для фронтенда

build: off  # Отключаем встроенную в AppVeyor систему сборки

build_script:
  - cd frontend && npm run build  # Собираем только фронтенд

test_script:
  - cd frontend && npm run lint && npm run test  # Тестируем только фронтенд

deploy_script:  # Скрипт развёртывания
  - git config --global credential.helper store  # Настройка Git для хранения учётных данных
  - git config --global user.name AppVeyor  # Установка имени пользователя для Git
  - git config --global user.email ci@appveyor.com  # Установка email для Git
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"  # Сохранение токена GitHub
  - cd frontend && npx gh-pages -d dist -u "appveyor-bot <ci@appveyor>"  # Деплой только папки dist фронтенда